- name: copy frontend conf file
  ansible.builtin.template:
    src: "{{ nginx_conf_src }}"  # check vars/main.yaml file  for value
    dest: "{{ nginx_conf_dest }}" # check vars/main.yaml file for value